name: Package

on:
  push
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install poetry
      run: |
        pip3 install poetry
    - name: install dependencies
      run: |
        poetry install
    - name: Deps
      run: |
        docker-compose -f test-stack.yml up -d
    - name: test
      env:
        SCYLLA_CHARYBDIS_ENDPOINT: http://localhost:34004
        SCYLLA_CHARYBDIS_USERNAME: basic
        SCYLLA_CHARYBDIS_PASSWORD: 123
      run: |
        poetry run pytest
